local pl = require('pl.path')
local this = pl.abspath(pl.abspath('.') .. '/' .. debug.getinfo(1).source:match("@(.*)$"))
local ep, encounter, standby

describe("EffortPoints", function()
    setup(function()
        loadfile(pl.abspath(pl.dirname(this) .. '/../../Test/TestSetup.lua'))(this, {})
        R2D2:OnInitialize()
        ep = R2D2:GetModule("EffortPoints")
        ep:OnInitialize()
        standby = R2D2:GetModule("Standby")
        standby:OnInitialize()
        R2D2:OnEnable()
        ep:OnEnable()
        encounter = R2D2.components.Models.Encounter
    end)

    teardown(function()
        After()
    end)

    describe("module", function()
        it("is initialized", function()
            assert.is.Not.Nil(ep)
            assert.is.True(ep:IsEnabled())
        end)
        it("handles encounter end", function()
            local e = encounter(710, 'Silithid Royalty', 9, 40, 1)
            ep:OnEncounterEnd(e)
            e = encounter(714, 'Princess Huhuran', 9, 40, 1)
            ep:OnEncounterEnd(e)
        end)
        it("handles scaling based upon instance", function()
            assert(ep:ScaleIfRequired(100) == 100)
        end)
    end)
end)